{{- if eq .Values.ingress.type "traefik" -}}
{{- /* Assuming .Values.ingress.traefik.ingressRoute.enabled exists from values.yaml */}}
{{- if .Values.ingress.traefik.ingressRoute.enabled -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  # Generate a unique name, e.g., frontend-dir-user-frontend
  name: {{ include "user-frontend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    # Include standard Helm labels
    {{- include "user-frontend.labels" . | nindent 4 }}
spec:
  entryPoints:
    # Use entrypoints defined in values, default to 'web'
    {{- range .Values.ingress.traefik.ingressRoute.entryPoints | default (list "web") }}
    - {{ . }}
    {{- end }}
  routes:
    # Route for Frontend (everything else - must be last rule for the host)
    - match: Host(`{{ required "ingress.traefik.ingressRoute.host is required" .Values.ingress.traefik.ingressRoute.host }}`) && PathPrefix(`/`)
      kind: Rule
      services:
        # Reference the frontend service defined in this chart
        - name: {{ include "user-frontend.fullname" . }}
          port: {{ .Values.service.port | default 80 }}
{{- end }}
{{- end }}