{{- if .Values.ingressRoute.enabled -}}

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  # Generate a unique name, e.g., frontend-dir-user-frontend
  name: {{ include "user-frontend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    # Include standard Helm labels
    {{- include "user-frontend.labels" . | nindent 4 }}
spec:
  entryPoints:
    # Use entrypoints defined in values, default to 'web'
    {{- range .Values.ingressRoute.entryPoints | default (list "web") }}
    - {{ . }}
    {{- end }}
  routes:
    # Route for Backend API (/api)
    - match: Host(`{{ required "ingressRoute.host must be set" .Values.ingressRoute.host }}`) && PathPrefix(`/api`)
      kind: Rule
      services:
        - name: {{ required "ingressRoute.backend.serviceName must be set" .Values.ingressRoute.backend.serviceName }}
          port: {{ .Values.ingressRoute.backend.port | default 3000 }}

    # Route for Frontend (everything else - must be last rule for the host)
    - match: Host(`{{ .Values.ingressRoute.host }}`) && PathPrefix(`/`)
      kind: Rule
      services:
        # Reference the frontend service defined in this chart
        - name: {{ include "user-frontend.fullname" . }}
          port: {{ .Values.service.port | default 80 }}
{{- end }}