{{- if eq .Values.ingress.type "kubernetes" -}}
{{- if .Values.ingress.kubernetes.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "user-frontend.fullname" . }}
  labels:
    {{- include "user-frontend.labels" . | nindent 4 }}
  {{- with .Values.ingress.kubernetes.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.kubernetes.className }}
  ingressClassName: {{ .Values.ingress.kubernetes.className }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.kubernetes.hostname | quote }}
      http:
        paths:
          {{- range .Values.ingress.kubernetes.paths }} # Ensure paths contains the root path object in values
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "user-frontend.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}
          {{- end }}
  {{- if .Values.ingress.kubernetes.tls }}
  tls:
    {{- range .Values.ingress.kubernetes.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }} 