kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: multi-tenant-dev
nodes:
  - role: control-plane
    # Add port mappings to allow external access to Ingress on localhost
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP
  - role: control-plane
  - role: control-plane
  - role: worker
  - role: worker
  - role: worker
