{{- if .Values.config.database.url -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "master-backend.fullname" . }}-secrets
  labels:
    {{- include "master-backend.labels" . | nindent 4 }}
stringData:
  DATABASE_URL: {{ .Values.config.database.url | quote }}
{{- end }} 