# GKE specific values for master-frontend

# Override Master Frontend image to use Artifact Registry
image:
  repository: asia-northeast3-docker.pkg.dev/nth-circlet-458901-h9/master-apps-repo/master-frontend # Replace with your actual AR path
  tag: "0.1.1" # Replace with the actual tag pushed to AR (e.g., from 6-BuildAndPushImages.sh)
  pullPolicy: IfNotPresent # Or Always

# Ingress configuration for GKE using standard Kubernetes Ingress
ingress:
  type: "kubernetes"
  kubernetes:
    enabled: true
    # className: "gce" # Usually default, uncomment if needed
    hostname: "master.jinseok9338.info" # MUST match the hostname used in master-backend for API proxying
    annotations:
      # Example: Use Google-managed SSL certificate (use the same one as backend)
      networking.gke.io/managed-certificates: master-cert
      # Use the reserved static IP address
      kubernetes.io/ingress.global-static-ip-name: master-static-ip
    # Define paths
    # Option B: Define explicit paths for frontend and backend API
    paths:
      - path: "/"
        pathType: Prefix
        # Backend for root path is the frontend service itself (implicitly handled by Helm/Ingress)
      - path: "/api/" # Use trailing slash for prefix match
        pathType: Prefix
        backend:
          service:
            name: master-backend-release # Helm release name of the master-backend service
            port:
              name: http # Name of the port in the master-backend service (usually http or mapped to 3000)
    # tls: [] # If TLS is configured
# Service account - Typically frontend doesn't need special Workload Identity
# serviceAccount:
#   create: true
#   annotations: {}
