{{- if eq .Values.ingress.type "traefik" -}}
{{- if .Values.ingress.traefik.ingressRoute.enabled -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "backend-api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "backend-api.labels" . | nindent 4 }}
spec:
  entryPoints:
    {{- range .Values.ingress.traefik.ingressRoute.entryPoints | default (list "web") }}
    - {{ . }}
    {{- end }}
  routes:
    - match: Host(`{{ required "ingress.traefik.ingressRoute.host must be set" .Values.ingress.traefik.ingressRoute.host }}`) 
      {{- if .Values.ingress.traefik.ingressRoute.pathPrefix }} # Optional path prefix
      && PathPrefix(`{{ .Values.ingress.traefik.ingressRoute.pathPrefix }}`)
      {{- end }}
      kind: Rule
      services:
        - name: {{ include "backend-api.fullname" . }}
          port: {{ .Values.service.port }}
      {{- if .Values.ingress.traefik.middleware.stripPrefix.enabled }} # Optional Middleware
      middlewares:
        - name: {{ printf "%s-stripprefix-api" (include "backend-api.fullname" .) }}
          namespace: {{ .Release.Namespace }}
      {{- end }}
{{- end }}
{{- end }} 