{{- if eq .Values.ingress.type "kubernetes" -}}
{{- if .Values.ingress.kubernetes.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "backend-api.fullname" . }}
  labels:
    {{- include "backend-api.labels" . | nindent 4 }}
  {{- with .Values.ingress.kubernetes.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.kubernetes.className }}
  ingressClassName: {{ .Values.ingress.kubernetes.className }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.kubernetes.hostname | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.kubernetes.path | default "/" }}
            pathType: {{ .Values.ingress.kubernetes.pathType | default "Prefix" }}
            backend:
              service:
                name: {{ include "backend-api.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
  {{- if .Values.ingress.kubernetes.tls }}
  tls:
    {{- range .Values.ingress.kubernetes.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }} 