{{- if .Values.ingressRoute.enabled -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "backend-api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "backend-api.labels" . | nindent 4 }}
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`{{ .Values.ingress.host }}`) && PathPrefix(`/api`)
      kind: Rule
      services:
        - name: {{ include "backend-api.fullname" . }}
          port: {{ .Values.service.port }}
      # Optional: Add middleware if needed, e.g., for stripping prefix if your app doesn't handle /api
      # middlewares:
      #   - name: {{ include "backend-api.fullname" . }}-stripprefix # Needs a corresponding Middleware object

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "backend-api.fullname" . }}-strip-prefix
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "backend-api.labels" . | nindent 4 }}
spec:
  stripPrefix:
    prefixes:
      - /{{ .Values.companyCode | lower }}/api
    # forceSlash: false
{{- end }} 