# Only create Middleware if enabled in values
{{- if eq .Values.ingress.type "traefik" -}}
{{- if .Values.ingress.traefik.middleware.stripPrefix.enabled -}}
---

apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  # Generate a unique name, e.g., backend-dir-backend-api-stripprefix-api
  name: {{ printf "%s-stripprefix-api" (include "backend-api.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    # Include standard Helm labels
    {{- include "backend-api.labels" . | nindent 4 }}
spec:
  stripPrefix:
    prefixes:
      # Use the pathPrefix defined for the IngressRoute, default to /api if not set
      - {{ .Values.ingress.traefik.ingressRoute.pathPrefix | default "/api" }}
{{- end -}}
{{- end -}} 