{{- if and (eq .Values.ingress.type "kubernetes") .Values.ingress.kubernetes.enabled -}}
{{- $fullName := include "master-frontend.fullname" . -}}
{{- $kubeSettings := .Values.ingress.kubernetes -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "master-frontend.labels" . | nindent 4 }}
  {{- with $kubeSettings.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if $kubeSettings.className }}
  ingressClassName: {{ $kubeSettings.className }}
  {{- end }}
  {{- if $kubeSettings.tls }}
  tls:
    {{- toYaml $kubeSettings.tls | nindent 4 }}
  {{- end }}
  rules:
    - host: {{ $kubeSettings.hostname | quote }}
      http:
        paths:
          {{- range $kubeSettings.paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                {{- if .backend }}
                # Allow specifying backend service explicitly (e.g., for /api proxy)
                name: {{ .backend.service.name }}
                port:
                  {{- if .backend.service.port.name }}
                  name: {{ .backend.service.port.name }}
                  {{- else if .backend.service.port.number }}
                  number: {{ .backend.service.port.number }}
                  {{- end }}
                {{- else }}
                # Default to the frontend service if backend not specified
                name: {{ $fullName }}
                port:
                  name: http # Assumes frontend service port is named http
                {{- end }}
          {{- end }}
{{- end }}